### ISSUE TITLE
PHP Fatal error due update on monolog

### ISSUE THREAD

**Issue by tommiekn** [bradmkjr/wp-log-viewer#2]
Hi @bradmkjr ,
Just tried script and seems theres an error with the latest version of monolog:

PHP Fatal error:  Declaration of WordPressHandler\WordPressHandler::write(array $record) must be compatible with Monolog\Handler\AbstractProcessingHandler::write(array $record): void in ../wp-content/plugins/label-grid-tools/vendor/bradmkjr/monolog-wordpress/src/WordPressHandler/WordPressHandler.php on line 15

To fix it you just need to edit WordPressHandler.php#15
to:
protected function write(array $record): void

Thanks

**Comment by bradmkjr** [comment]
If you could do a pull request, I will happily accept it. I'm not setup to
push to this repository right now.

Brad

**Comment by bradmkjr** [comment]
Actually, one of the other developers on the project has pushed that change, but they didn't bump up the version.

https://github.com/bradmkjr/monolog-wordpress/commit/e2619f57920b1aa99ac6062e49371cda25306ba6#diff-9b3a792ccab609e8bceda9344c1beb69

I will look at bumping up the version to get the change pushed out.
